In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [11]:
df = pd.read_csv('Earthquake_Data.csv', delimiter=r'\s+')

In [13]:
display(df)

,Date(YYYY/MM/DD),Time,Latitude,Longitude,Depth,Mag,Magt,Nst,Gap,Clo,RMS,SRC,EventID
0,1966/07/01,09:41:21.82,35.9463,-120.4700,12.26,3.20,Mx,7,171,20,0.02,NCSN,-4540462
1,1966/07/02,12:08:34.25,35.7867,-120.3265,8.99,3.70,Mx,8,86,3,0.04,NCSN,-4540520
2,1966/07/02,12:16:14.95,35.7928,-120.3353,9.88,3.40,Mx,8,89,2,0.03,NCSN,-4540521
3,1966/07/02,12:25:06.12,35.7970,-120.3282,9.09,3.10,Mx,8,101,3,0.08,NCSN,-4540522
4,1966/07/05,18:54:54.36,35.9223,-120.4585,7.86,3.10,Mx,9,161,14,0.04,NCSN,-4540594
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18025,2007/12/19,12:14:09.62,34.1438,-116.9822,7.03,4.06,ML,10,73,14,0.08,NCSN,40207706
18026,2007/12/21,12:14:56.45,37.3078,-121.6735,8.47,3.08,ML,114,45,5,0.12,NCSN,51192926
18027,2007/12/23,21:43:43.54,37.2127,-117.8230,10.00,3.54,ML,45,176,40,0.07,NCSN,51193070
18028,2007/12/28,01:59:42.40,36.5292,-121.1133,5.99,3.04,ML,70,45,4,0.06,NCSN,51193343
18029,2007/12/28,23:20:28.12,38.7710,-122.7370,2.34,3.40,Mw,49,37,1,0.07,NCSN,51193419

# Preprocessing

### Adding Date and Time as new Index of the dataset

In [ ]:
new_column_names = ["Date(YYYY/MM/DD)",  "Time(UTC)", "Latitude(deg)", "Longitude(deg)", "Depth(km)", "Magnitude(ergs)", 
                    "Magnitude_type", "No_of_Stations", "Gap", "Close", "RMS", "SRC", "EventID"]

df.columns = new_column_names
ts = pd.to_datetime(df["Date(YYYY/MM/DD)"] + " " + df["Time(UTC)"])
df = df.drop(["Date(YYYY/MM/DD)", "Time(UTC)"], axis=1)
df.index = ts
display(df)

,Latitude(deg),Longitude(deg),Depth(km),Magnitude(ergs),Magnitude_type,No_of_Stations,Gap,Close,RMS,SRC,EventID
1966-07-01 09:41:21.820,35.9463,-120.4700,12.26,3.20,Mx,7,171,20,0.02,NCSN,-4540462
1966-07-02 12:08:34.250,35.7867,-120.3265,8.99,3.70,Mx,8,86,3,0.04,NCSN,-4540520
1966-07-02 12:16:14.950,35.7928,-120.3353,9.88,3.40,Mx,8,89,2,0.03,NCSN,-4540521
1966-07-02 12:25:06.120,35.7970,-120.3282,9.09,3.10,Mx,8,101,3,0.08,NCSN,-4540522
1966-07-05 18:54:54.360,35.9223,-120.4585,7.86,3.10,Mx,9,161,14,0.04,NCSN,-4540594
...,...,...,...,...,...,...,...,...,...,...,...
2007-12-19 12:14:09.620,34.1438,-116.9822,7.03,4.06,ML,10,73,14,0.08,NCSN,40207706
2007-12-21 12:14:56.450,37.3078,-121.6735,8.47,3.08,ML,114,45,5,0.12,NCSN,51192926
2007-12-23 21:43:43.540,37.2127,-117.8230,10.00,3.54,ML,45,176,40,0.07,NCSN,51193070
2007-12-28 01:59:42.400,36.5292,-121.1133,5.99,3.04,ML,70,45,4,0.06,NCSN,51193343
2007-12-28 23:20:28.120,38.7710,-122.7370,2.34,3.40,Mw,49,37,1,0.07,NCSN,51193419

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 18030 entries, 1966-07-01 09:41:21.820000 to 2007-12-28 23:20:28.120000
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Latitude(deg)    18030 non-null  float64
 1   Longitude(deg)   18030 non-null  float64
 2   Depth(km)        18030 non-null  float64
 3   Magnitude(ergs)  18030 non-null  float64
 4   Magnitude_type   18030 non-null  object
 5   No_of_Stations   18030 non-null  int64
 6   Gap              18030 non-null  int64
 7   Close            18030 non-null  int64
 8   RMS              18030 non-null  float64
 9   SRC              18030 non-null  object
 10  EventID          18030 non-null  int64
dtypes: float64(5), int64(4), object(2)
memory usage: 1.7+ MB

### Exporting Preprocessed Data

In [19]:
file_name = 'Preprocessed_Earthquake_Data.xlsx'

df.to_excel(file_name)
print('DataFrame is written to Excel File successfully.')

DataFrame is written to Excel File successfully.

### Partition the data into Training and Testing data

In [ ]:
from sklearn.model_selection import train_test_split


X = df[['Latitude(deg)', 'Longitude(deg)', 'Depth(km)', 'No_of_Stations']]
#target output
y = df['Magnitude(ergs)']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Linear regression

In [23]:
from sklearn.linear_model import LinearRegression

# Train the linear regression model
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [25]:
new_data = [[33.89, -118.40, 16.17, 11], [37.77, -122.42, 8.05, 15]]
new_pred = regressor.predict(new_data)
print("New predictions:", new_pred)

New predictions: [3.447483  3.3338426]

In [28]:
from sklearn.metrics import r2_score, mean_squared_error

scores= {"Model name": ["Linear regression", "Random Forest"], "mse": [], "R^2": []}

# Predict on the testing set
y_pred = regressor.predict(X_test)

# Compute R^2 and MSE
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

scores['mse'].append(mse)
scores['R^2'].append(r2)

print("R^2: {:.2f}, MSE: {:.2f}".format(r2, mse))

R^2: 0.02, MSE: 0.19

### Random Forest Regressor

In [29]:
from sklearn.ensemble import RandomForestRegressor

# Initialize a random forest regressor with 100 trees
rf = RandomForestRegressor(n_estimators=100, random_state=42)

# Fit the regressor to the training data
rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [32]:
rf_new_predict =rf.predict(new_data)
print("RF prdiction: ", rf_new_predict)

RF prdiction:  [3.3164 3.3844]

In [30]:
# Predict the target variable on the test data
y_pred = rf.predict(X_test)

# Evaluate the performance of the model using mean squared error and R^2 score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

scores['mse'].append(mse)
scores['R^2'].append(r2)

print('Mean Squared Error: ', mse)
print('R^2 Score: ', r2)

Mean Squared Error:  0.1662872549445369
R^2 Score:  0.13602430220850115

In [31]:
scores_df = pd.DataFrame(scores)
display(scores_df)

          Model name       mse       R^2
0  Linear regression  0.187942  0.023514
1      Random Forest  0.166287  0.136024